services:
  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: go_bot
      TZ: Europe/Moscow
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: app
    environment:
      TZ: Europe/Moscow
    networks: 
      - default
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata: